create table products (
	id INT,
	ProductName VARCHAR(50),
	CategoryName VARCHAR(50)
);
insert into products (id, ProductName, CategoryName) values (1, 'Apples - Spartan', 'CAD');
insert into products (id, ProductName, CategoryName) values (2, 'Cheese - Stilton', 'MXN');
insert into products (id, ProductName, CategoryName) values (3, 'Cheese - Stilton', 'USD');
insert into products (id, ProductName, CategoryName) values (4, 'Water - San Pellegrino', 'CNY');
insert into products (id, ProductName, CategoryName) values (5, 'Food Colouring - Red', 'IDR');
insert into products (id, ProductName, CategoryName) values (6, 'Truffle - Peelings', 'USD');
insert into products (id, ProductName, CategoryName) values (7, 'Cheese - Shred Cheddar / Mozza', 'EUR');
insert into products (id, ProductName, CategoryName) values (8, 'Pear - Asian', 'AMD');
insert into products (id, ProductName, CategoryName) values (9, 'Container Clear 8 Oz', 'CNY');
insert into products (id, ProductName, CategoryName) values (10, 'Beef - Bones, Cut - Up', 'IDR');
insert into products (id, ProductName, CategoryName) values (11, 'Ginsing - Fresh', 'IDR');
insert into products (id, ProductName, CategoryName) values (12, 'Seedlings - Mix, Organic', 'EUR');
insert into products (id, ProductName, CategoryName) values (13, 'Beef - Cooked, Corned', 'PHP');
insert into products (id, ProductName, CategoryName) values (14, 'Cream - 35%', 'RUB');
insert into products (id, ProductName, CategoryName) values (15, 'Shrimp - Black Tiger 16/20', 'EUR');
insert into products (id, ProductName, CategoryName) values (16, 'Muskox - French Rack', 'RUB');
insert into products (id, ProductName, CategoryName) values (17, 'Pepper - Green', 'PLN');
insert into products (id, ProductName, CategoryName) values (18, 'Wine - Red, Marechal Foch', 'CNY');
insert into products (id, ProductName, CategoryName) values (19, 'Pea - Snow', 'VEF');
insert into products (id, ProductName, CategoryName) values (20, 'Muffin Batt - Choc Chk', 'VEF');
insert into products (id, ProductName, CategoryName) values (21, 'Wild Boar - Tenderloin', 'USD');
insert into products (id, ProductName, CategoryName) values (22, 'Cheese - Mozzarella', 'IDR');
insert into products (id, ProductName, CategoryName) values (23, 'Wine - Mondavi Coastal Private', 'IDR');
insert into products (id, ProductName, CategoryName) values (24, 'Octopus - Baby, Cleaned', 'IDR');
insert into products (id, ProductName, CategoryName) values (25, 'Flounder - Fresh', 'PHP');
insert into products (id, ProductName, CategoryName) values (26, 'Seaweed Green Sheets', 'CAD');
insert into products (id, ProductName, CategoryName) values (27, 'Bread - White Epi Baguette', 'MAD');
insert into products (id, ProductName, CategoryName) values (28, 'Garlic Powder', 'KZT');
insert into products (id, ProductName, CategoryName) values (29, 'Mustard Prepared', 'CNY');
insert into products (id, ProductName, CategoryName) values (30, 'Grouper - Fresh', 'RUB');
insert into products (id, ProductName, CategoryName) values (31, 'Lemonade - Strawberry, 591 Ml', 'SEK');
insert into products (id, ProductName, CategoryName) values (32, 'Puree - Passion Fruit', 'XAF');
insert into products (id, ProductName, CategoryName) values (33, 'Durian Fruit', 'PLN');
insert into products (id, ProductName, CategoryName) values (34, 'Paste - Black Olive', 'RUB');
insert into products (id, ProductName, CategoryName) values (35, 'Ecolab - Hand Soap Form Antibac', 'PAB');
insert into products (id, ProductName, CategoryName) values (36, 'Creme De Cacao Mcguines', 'OMR');
insert into products (id, ProductName, CategoryName) values (37, 'Wine - Taylors Reserve', 'EUR');
insert into products (id, ProductName, CategoryName) values (38, 'Wine - Crozes Hermitage E.', 'EUR');
insert into products (id, ProductName, CategoryName) values (39, 'Garbage Bags - Clear', 'EUR');
insert into products (id, ProductName, CategoryName) values (40, 'Chambord Royal', 'EUR');
insert into products (id, ProductName, CategoryName) values (41, 'Thyme - Lemon, Fresh', 'KWD');
insert into products (id, ProductName, CategoryName) values (42, 'Oil - Olive Bertolli', 'PLN');
insert into products (id, ProductName, CategoryName) values (43, 'Puree - Kiwi', 'KZT');
insert into products (id, ProductName, CategoryName) values (44, 'Ice Cream Bar - Hagen Daz', 'PHP');
insert into products (id, ProductName, CategoryName) values (45, 'Container Clear 8 Oz', 'PHP');
insert into products (id, ProductName, CategoryName) values (46, 'Wine - Red, Gallo, Merlot', 'IDR');
insert into products (id, ProductName, CategoryName) values (47, 'Snapple Raspberry Tea', 'JPY');
insert into products (id, ProductName, CategoryName) values (48, 'General Purpose Trigger', 'JMD');
insert into products (id, ProductName, CategoryName) values (49, 'Muffin Orange Individual', 'CNY');
insert into products (id, ProductName, CategoryName) values (50, 'Sauce - Bernaise, Mix', 'CNY');
insert into products (id, ProductName, CategoryName) values (51, 'Pepper - White, Whole', 'RUB');
insert into products (id, ProductName, CategoryName) values (52, 'Wine - Red, Pelee Island Merlot', 'CNY');
insert into products (id, ProductName, CategoryName) values (53, 'Yogurt - Plain', 'BRL');
insert into products (id, ProductName, CategoryName) values (54, 'Prunes - Pitted', 'NOK');
insert into products (id, ProductName, CategoryName) values (55, 'Flour - Rye', 'UAH');
insert into products (id, ProductName, CategoryName) values (56, 'Pastry - Butterscotch Baked', 'NZD');
insert into products (id, ProductName, CategoryName) values (57, 'Wine - Chardonnay South', 'IDR');
insert into products (id, ProductName, CategoryName) values (58, 'Orange - Canned, Mandarin', 'RUB');
insert into products (id, ProductName, CategoryName) values (59, 'Wine La Vielle Ferme Cote Du', 'SLL');
insert into products (id, ProductName, CategoryName) values (60, 'Wine - Rosso Toscano Igt', 'EUR');
insert into products (id, ProductName, CategoryName) values (61, 'Syrup - Monin - Granny Smith', 'CNY');
insert into products (id, ProductName, CategoryName) values (62, 'Bread - Pullman, Sliced', 'PHP');
insert into products (id, ProductName, CategoryName) values (63, 'Corn Kernels - Frozen', 'MNT');
insert into products (id, ProductName, CategoryName) values (64, 'Bread Base - Italian', 'JPY');
insert into products (id, ProductName, CategoryName) values (65, 'Beef - Inside Round', 'PLN');
insert into products (id, ProductName, CategoryName) values (66, 'Cookies - Assorted', 'PEN');
insert into products (id, ProductName, CategoryName) values (67, 'V8 Pet', 'SEK');
insert into products (id, ProductName, CategoryName) values (68, 'Coffee - Egg Nog Capuccino', 'HRK');
insert into products (id, ProductName, CategoryName) values (69, 'Wine - Rosso Del Veronese Igt', 'ALL');
insert into products (id, ProductName, CategoryName) values (70, 'Pork - Caul Fat', 'PHP');
insert into products (id, ProductName, CategoryName) values (71, 'Rice - 7 Grain Blend', 'ILS');
insert into products (id, ProductName, CategoryName) values (72, 'Pepper - Yellow Bell', 'THB');
insert into products (id, ProductName, CategoryName) values (73, 'Croissant, Raw - Mini', 'EUR');
insert into products (id, ProductName, CategoryName) values (74, 'Sauce - Rosee', 'CNY');
insert into products (id, ProductName, CategoryName) values (75, 'Chestnuts - Whole,canned', 'IDR');
insert into products (id, ProductName, CategoryName) values (76, 'Spice - Pepper Portions', 'USD');
insert into products (id, ProductName, CategoryName) values (77, 'Chips Potato Salt Vinegar 43g', 'RUB');
insert into products (id, ProductName, CategoryName) values (78, 'Smoked Tongue', 'USD');
insert into products (id, ProductName, CategoryName) values (79, 'Cake - Mini Potato Pancake', 'UAH');
insert into products (id, ProductName, CategoryName) values (80, 'Sprite - 355 Ml', 'RUB');
insert into products (id, ProductName, CategoryName) values (81, 'Beer - Tetleys', 'COP');
insert into products (id, ProductName, CategoryName) values (82, 'Vermouth - Sweet, Cinzano', 'IDR');
insert into products (id, ProductName, CategoryName) values (83, 'Melon - Honey Dew', 'BRL');
insert into products (id, ProductName, CategoryName) values (84, 'Peas - Pigeon, Dry', 'BRL');
insert into products (id, ProductName, CategoryName) values (85, 'Wine - Cava Aria Estate Brut', 'PLN');
insert into products (id, ProductName, CategoryName) values (86, 'Cabbage - Red', 'UAH');
insert into products (id, ProductName, CategoryName) values (87, 'Mix - Cappucino Cocktail', 'EUR');
insert into products (id, ProductName, CategoryName) values (88, 'Bread - English Muffin', 'JPY');
insert into products (id, ProductName, CategoryName) values (89, 'Ecolab - Mikroklene 4/4 L', 'VEF');
insert into products (id, ProductName, CategoryName) values (90, 'Beef - Cow Feet Split', 'EUR');
insert into products (id, ProductName, CategoryName) values (91, 'Ice Cream - Super Sandwich', 'UAH');
insert into products (id, ProductName, CategoryName) values (92, 'Gatorade - Lemon Lime', 'KES');
insert into products (id, ProductName, CategoryName) values (93, 'Crackers - Graham', 'CNY');
insert into products (id, ProductName, CategoryName) values (94, 'Chicken Breast Halal', 'RUB');
insert into products (id, ProductName, CategoryName) values (95, 'Soup - Base Broth Chix', 'XCD');
insert into products (id, ProductName, CategoryName) values (96, 'Ice Cream - Super Sandwich', 'BYR');
insert into products (id, ProductName, CategoryName) values (97, 'Tomato - Green', 'CNY');
insert into products (id, ProductName, CategoryName) values (98, 'Flavouring - Raspberry', 'ETB');
insert into products (id, ProductName, CategoryName) values (99, 'Oil - Olive', 'EUR');
insert into products (id, ProductName, CategoryName) values (100, 'Nut - Cashews, Whole, Raw', 'COP');
insert into products (id, ProductName, CategoryName) values (101, 'Beef - Bones, Cut - Up', 'RUB');
insert into products (id, ProductName, CategoryName) values (102, 'Energy Drink - Franks Original', 'USD');
insert into products (id, ProductName, CategoryName) values (103, 'Cocoa Feuilletine', 'PEN');
insert into products (id, ProductName, CategoryName) values (104, 'Pastry - Lemon Danish - Mini', 'PHP');
insert into products (id, ProductName, CategoryName) values (105, 'Wine - Gato Negro Cabernet', 'CNY');
insert into products (id, ProductName, CategoryName) values (106, 'Latex Rubber Gloves Size 9', 'CNY');
insert into products (id, ProductName, CategoryName) values (107, 'Melon - Cantaloupe', 'CNY');
insert into products (id, ProductName, CategoryName) values (108, 'Beef - Inside Round', 'EUR');
insert into products (id, ProductName, CategoryName) values (109, 'Chicken - Livers', 'CNY');
insert into products (id, ProductName, CategoryName) values (110, 'Tumeric', 'PEN');
insert into products (id, ProductName, CategoryName) values (111, 'Wine - Placido Pinot Grigo', 'USD');
insert into products (id, ProductName, CategoryName) values (112, 'English Muffin', 'SEK');
insert into products (id, ProductName, CategoryName) values (113, 'Quail - Eggs, Fresh', 'GMD');
insert into products (id, ProductName, CategoryName) values (114, 'Steam Pan - Half Size Deep', 'IDR');
insert into products (id, ProductName, CategoryName) values (115, 'Compound - Passion Fruit', 'IDR');
insert into products (id, ProductName, CategoryName) values (116, 'Steamers White', 'RSD');
insert into products (id, ProductName, CategoryName) values (117, 'Muffin Mix - Blueberry', 'NGN');
insert into products (id, ProductName, CategoryName) values (118, 'Ham Black Forest', 'USD');
insert into products (id, ProductName, CategoryName) values (119, 'Cheese - Mozzarella', 'PHP');
insert into products (id, ProductName, CategoryName) values (120, 'Orange - Canned, Mandarin', 'ARS');
insert into products (id, ProductName, CategoryName) values (121, 'Sobe - Berry Energy', 'IDR');
insert into products (id, ProductName, CategoryName) values (122, 'Shallots', 'GMD');
insert into products (id, ProductName, CategoryName) values (123, 'Anisette - Mcguiness', 'EUR');
insert into products (id, ProductName, CategoryName) values (124, 'Beer - Sleemans Cream Ale', 'CNY');
insert into products (id, ProductName, CategoryName) values (125, 'Table Cloth 54x54 White', 'XAF');
insert into products (id, ProductName, CategoryName) values (126, 'Graham Cracker Mix', 'VND');
insert into products (id, ProductName, CategoryName) values (127, 'Sachet', 'CNY');
insert into products (id, ProductName, CategoryName) values (128, 'Pork - Tenderloin, Fresh', 'JPY');
insert into products (id, ProductName, CategoryName) values (129, 'Longos - Assorted Sandwich', 'IDR');
insert into products (id, ProductName, CategoryName) values (130, 'Sugar - Individual Portions', 'SEK');
insert into products (id, ProductName, CategoryName) values (131, 'Wood Chips - Regular', 'PHP');
insert into products (id, ProductName, CategoryName) values (132, 'Chocolate - Pistoles, Lactee, Milk', 'EUR');
insert into products (id, ProductName, CategoryName) values (133, 'Rosemary - Dry', 'UAH');
insert into products (id, ProductName, CategoryName) values (134, 'Wine - Ej Gallo Sierra Valley', 'CNY');
insert into products (id, ProductName, CategoryName) values (135, 'Jerusalem Artichoke', 'NGN');
insert into products (id, ProductName, CategoryName) values (136, 'Nacho Chips', 'UAH');
insert into products (id, ProductName, CategoryName) values (137, 'Tea - Herbal I Love Lemon', 'PLN');
insert into products (id, ProductName, CategoryName) values (138, 'Grapes - Red', 'COP');
insert into products (id, ProductName, CategoryName) values (139, 'Pork - Bacon Cooked Slcd', 'BYR');
insert into products (id, ProductName, CategoryName) values (140, 'Chick Peas - Canned', 'CZK');
insert into products (id, ProductName, CategoryName) values (141, 'Aromat Spice / Seasoning', 'RUB');
insert into products (id, ProductName, CategoryName) values (142, 'Banana Turning', 'PHP');
insert into products (id, ProductName, CategoryName) values (143, 'Lettuce - Iceberg', 'CNY');
insert into products (id, ProductName, CategoryName) values (144, 'Wine - Coteaux Du Tricastin Ac', 'CNY');
insert into products (id, ProductName, CategoryName) values (145, 'Crackers - Water', 'EUR');
insert into products (id, ProductName, CategoryName) values (146, 'Cookie Dough - Chunky', 'CNY');
insert into products (id, ProductName, CategoryName) values (147, 'Flower - Carnations', 'RUB');
insert into products (id, ProductName, CategoryName) values (148, 'Milk - Buttermilk', 'CNY');
insert into products (id, ProductName, CategoryName) values (149, 'Tart Shells - Sweet, 4', 'UGX');
insert into products (id, ProductName, CategoryName) values (150, 'Pears - Bartlett', 'ARS');
